name: Build

# Build on every branch push, tag push, and pull request change:
on: [push, pull_request_target]

jobs:
  build_repo:
    name: Build repo (${{ matrix.version }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version: [us]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install package requirements
      run: sudo apt-get install -y make git build-essential clang binutils-mips-linux-gnu gcc-mips-linux-gnu python3 python3-pip clang-format-11 clang-tidy-11

    - name: Install Python dependencies
      run: python3 -m pip install -r requirements.txt

    - name: Get extra dependencies
      uses: actions/checkout@v4
      with:
        repository: ${{ secrets.SECRETREPO }}
        token: ${{ secrets.SECRETTOKEN }}
        path: deps_repo
    - name: Get the dependency
      run: cp -r deps_repo/goin_quackers/* disk/

    - name: Setup
      run: make setup -j $(nproc) VERSION=${{ matrix.version }}

    - name: Disassemble and extraction
      run: make extract -j $(nproc) VERSION=${{ matrix.version }}

    - name: Build
      run: make -j $(nproc) WERROR=1 VERSION=${{ matrix.version }}

    # - name: Print progress
    #   run: python3 tools/progress.py --version ${{ matrix.version }}

    # - name: Upload frogress
    #   if: ${{ github.ref == 'refs/heads/main' && github.event_name != 'pull_request_target' }}
    #   run: python3 tools/upload_frogress.py ${{ matrix.version }} --apikey ${{ secrets.PROGRESS_API_KEY }}

    - name: Upload map
      uses: actions/upload-artifact@v3
      with:
        name: goin_quackers.${{ matrix.version }}.map
        path: build/${{ matrix.version }}/goin_quackers.${{ matrix.version }}.map
